name: PyInstaller Check

on: [push]

jobs:
  check:
    name: Check PyInstaller for Python ${{ matrix.python_version }} (${{ matrix.architecture }})
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11"]
        architecture: [x64, x86]
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.architecture }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: poetry install

      - name: Build PyInstaller package
        run: poetry run pyinstaller unlicense.spec

      - name: "Upload PyInstaller Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: unlicense-py${{ matrix.python_version }}-${{ matrix.architecture }}
          path: dist/*.exe
          retention-days: 3
